### ISSUE TITLE
Unable to edit service name - models component

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-models#10]
We should do the btc-models parts of https://github.com/Tour-de-Force/btc-app/issues/55

**Comment by samfalconer** [comment]
IMPORTANT: This has to be tested and pushed with https://github.com/Tour-de-Force/btc-app/issues/55

**Comment by Jeremy-Friedman** [comment]
Ship it.

**Comment by samfalconer** [comment]
Merged.
