### ISSUE TITLE
Move comment model inside point schema

### ISSUE THREAD

**Issue by samfalconer** [Tour-de-Force/btc-models#21]
Since comments are strongly tied to points, just have them in an array on the point itself so we don't need to worry about replicating them and whatnot separately.

We will eventually need better server-side validation of comments and flag data to make sure people aren't messing with them in weird ways.

Don't rollback the separate comment DB stuff here to keep this simple, we can do that in the original bugs if this works out.

**Comment by samfalconer** [comment]
Pushing now to make the build. Holding open for review.

**Comment by asmasattar** [comment]
Works well. Everything looks good to me.

**Comment by samfalconer** [comment]
Already merged. Closing.
