### ISSUE TITLE
Remove username, replace with email address 

### ISSUE THREAD

**Issue by asmasattar** [Tour-de-Force/btc-models#3]
We should remove the username at the model layer. We will be using the user's email address in its place. Link to btc-app, username removed from form: https://github.com/Tour-de-Force/btc-app/issues/33

**Comment by samfalconer** [comment]
Looks good to 🛳!

**Comment by samfalconer** [comment]
Looks good to 🛳!

**Comment by asmasattar** [comment]
Merged.
